config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :homes
  resources :books
  root to: 'homes#index'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  validates :body,presence: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
   @book =Book.new
  end
  def index
   @book =Book.new
   @books =Book.all

  end
  
 def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
    else
      @books= Book.all
      render :index
    end  
 end
  
  def show
    @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    redirect_to book_path(book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def new
  end      

  def index
    
  end

  def show
   @book =Book.all
  end

  def edit
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
  <h4>body</h4>
  <%= f.text_area :body %>
  <%= f.submit 'UpdateBook' %>
<% end %>

<%= link_to"show",book_path(@book)%>|<%= link_to"back","/books"%>

app/views/books/index.html.erb
 <h1>Books</h1>

<table>
    <tr>
        <th>Title</th>

        <th>Body</th>

        <th></th>
    </tr>
    <% @books.each do |book| %>
    <tr>

        <td><%= book.title %> </td>
        <td><%= book.body %></td>

        <td><%= link_to"Show",book_path(book)%></td>
        <td><%= link_to"Edit",edit_book_path(book.id)%></td>
        <td><%= link_to"Destroy",book_path(book), method: :delete, "data-confirm" => "Are you sure？"%></td>

    </tr>
     <%end%>
</table>

<h3>New book</h3>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>
<h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books</h1>
<table>
    <tr>
        <tb>title</tb>
        <tb>body</tb>
        <tb></tb>
    </tr>
    <tr>
        <%= @book.each do |book| %>
        <tb> <%= book.title %></tb>
        <tb><%= book.body %></tb>
       <% end %>
    </tr>
    <tr>
      <tb><%= link_to book.title, "/books/#{book.id}" %></tb>
      <tb></tb>
    </tr>
</table>
<h3>New book</h3>
<%= form_with model: @book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>
	
  <h4>body</h4>
  <%= f.text_area :body %>
	
  <%= f.submit 'CreateBook' %>
<% end %>

app/views/books/show.html.erb
<p>Book was successfully created.</p>

<h2>title</h2>
<p><%= @book.title %></p>

<h2>body</h2>
<p><%= @book.body %></p>

<%= link_to"edit",edit_book_path(@book.id)%>|<%= link_to"back","/books"%>

app/views/homes/edit.html.erb
<h1>Homes#edit</h1>
<p>Find me in app/views/homes/edit.html.erb</p>

app/views/homes/index.html.erb
 <h1>ようこそ Bookers へ！</h1>

<p>Bookers では、さまざまな書籍に関するあなたの意見や

印象を共有し交換することができます</p>

<%=link_to "start","books" %>

app/views/homes/new.html.erb
<h1>ようこそ Bookers へ！</h1>

<p>Bookers では、さまざまな書籍に関するあなたの意見や

印象を共有し交換することができます</p>

<%=link_to "start","/books" %>

app/views/homes/show.html.erb
 <% @book.each do |book| %>
   <h3>:title</h3><tb> <%= book.title %></tb>
   <h3>:body</h3><tb><%= book.body %></tb>
 <% end %>

   <%= link_to"edit",edit_book_path(@book.id)%>|<%= link_to"back","/books"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

app/views/lists/show.html.erb
<h1>Lists#show</h1>
<p>Find me in app/views/lists/show.html.erb</p>